### ISSUE TITLE
How do you create a category?

### ISSUE THREAD

**Issue by sattelbergerp** [hyoyou/recipe-rails-app#1]
I cant find a link to create a new category. Trying /categories/new gives me the error "Couldn't find Category with 'id'=new" and the category option on the new recipe page just has the option "Please Select One"

also it would be nice if there was a link to go back to the root page ("/") in the header.

**Comment by hyoyou** [comment]
Hi!

I didn't give the option for users to create a category yet but will work on that in the future! The new recipe page should have a drop down of the available categories when you click on "Please Select One"

I agree and should get those links in the header! I am still working on this app at the moment, and really appreciate the feedback! Thanks for looking into my project :)

**Comment by sattelbergerp** [comment]
Thanks for the quick response!
I saw the blog post and assumed it was submitted/complete. After going into rails console and manually creating a category. the app is very unpolished but I really like what is there. I would love to see what it looks like completed.
Keep up the good work!

**Comment by hyoyou** [comment]
Yeah, I still have a long way to go, especially with the custom writer attribute (I am really stuck on that one)! One of the rails final project study groups suggested us to submit the project prior to having it completed because scheduling availability is very low. 

Thank you so much :) Hope to see you around!
